---
global:
  edition: ce
  hosts:
    domain: gitlab.bmath.nyc
    hostSuffix:
    https: true
    externalIP: 147.75.67.248
  ingress:
    configureCertmanager: true
    annotations: {}
    enabled: false
    tls: {}
  
gitlab:
  gitaly:
    persistence:
      storageClass: cstor-stretched
      size: 50Gi
postgresql:
  persistence:
    storageClass: cstor
    size: 8Gi
minio:
  persistence:
    storageClass: cstor-stretched
    size: 10Gi
# not sure why the following doesn't work, but...
redis:
  persistence:
    storageClass: openebs-hostpath
    size: 5Gi

certmanager-issuer:
  email: bmath@mayadata.io
